
baseURL = "https://agren.cc"
languageCode = 'en-us'
DefaultContentLanguage = "en"
title = "agren.cc"
theme = "terminal"
summarylength = 10
enableEmoji = true
enableRobotsTXT = false
paginate = 5
publishDir = "."

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
  fullWidthTheme = false
  centerTheme = true
  contentTypeName = "p"
  themeColor = "blue"

[languages]
  [languages.en]
    languageName = "English"
    title = "agren.cc"

    [languages.en.params]
      menuMore = "Show more"
      readMore = "Read more"
      readOtherPosts = "Read other posts"
      newerPosts = "Newer posts"
      olderPosts = "Older posts"
      missingContentMessage = "Page not found..."
      missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "agren.cc"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About/Contact"
        url = "/about/index.html"

[author]
  name = 'agren.cc'