
baseURL = "https://agren.cc"
languageCode = 'en-us'
DefaultContentLanguage = "en"
title = "agren.cc"
summarylength = 10
enableEmoji = true
enableRobotsTXT = false
publishDir = "."

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[module]
[[module.imports]]
path = 'github.com/panr/hugo-theme-terminal/v4'

[pagination]
pagerSize = 10

[params]
author = 'agren.cc'
autoCover = true
fullWidthTheme = false
centerTheme = true
contentTypeName = "p"
customCSS = ["terminal.css"]

[languages]
[languages.en]
languageName = "English"
title = "agren.cc"

[languages.en.params]
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
missingContentMessage = "This page does not exist."
missingBackButtonLabel = "Enable Guidance Subsystem"

[languages.en.params.logo]
logoText = "agren.cc"
logoHomeLink = "/"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "about"
name = "about"
url = "/about/index.html"
[[languages.en.menu.main]]
identifier = "mastodon"
name = "mastodon"
url = "https://telegrafverket.cc/@linus"
