
baseURL = "https://agren.cc"
languageCode = 'en-us'
DefaultContentLanguage = "en"
title = "agren.cc"
theme = "terminal"
summarylength = 10
enableEmoji = true
enableRobotsTXT = false
publishDir = "."

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[pagination]
pagerSize = 10

[params]
fullWidthTheme = false
centerTheme = true
contentTypeName = "p"
themeColor = "blue"

[languages]
[languages.en]
languageName = "English"
title = "agren.cc"

[languages.en.params]
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
missingContentMessage = "This page does not exist."
missingBackButtonLabel = "Enable Guidance Subsystem"

[languages.en.params.logo]
logoText = "agren.cc"
logoHomeLink = "/"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "about"
name = "About/Contact"
url = "/about/index.html"

[author]
name = 'agren.cc'
