
baseURL = "https://agren.cc"
languageCode = 'en-us'
DefaultContentLanguage = "en"
title = "agren.cc"
summarylength = 10
enableEmoji = true
enableRobotsTXT = false
publishDir = "."

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[module]
[[module.imports]]
path = 'github.com/panr/hugo-theme-terminal/v4'

[pagination]
pagerSize = 10

[params]
author = 'agren.cc'
autoCover = true
fullWidthTheme = false
centerTheme = true
contentTypeName = "p"
customCSS = ["terminal.css"]

[languages]
[languages.en]
languageName = "English"
title = "agren.cc"

[languages.en.params]
menuMore = "Show more"
readMore = "Read more"
readOtherPosts = "Read other posts"
newerPosts = "Newer posts"
olderPosts = "Older posts"
missingContentMessage = "The missile knows where it is at all times. It knows this because it knows where it isn't. By subtracting where it is from where it isn't, or where it isn't from where it is (whichever is greater), it obtains a difference, or deviation. The guidance subsystem uses deviations to generate corrective commands to drive the missile from a position where it is to a position where it isn't, and arriving at a position where it wasn't, it now is. Consequently, the position where it is, is now the position that it wasn't, and it follows that the position that it was, is now the position that it isn't. In the event that the position that it is in is not the position that it wasn't, the system has acquired a variation, the variation being the difference between where the missile is, and where it wasn't. If variation is considered to be a significant factor, it too may be corrected by the GEA. However, the missile must also know where it was. The missile guidance computer scenario works as follows. Because a variation has modified some of the information the missile has obtained, it is not sure just where it is. However, it is sure where it isn't, within reason, and it knows where it was. It now subtracts where it should be from where it wasn't, or vice-versa, and by differentiating this from the algebraic sum of where it shouldn't be, and where it was, it is able to obtain the deviation and its variation, which is called error."
missingBackButtonLabel = "Enable Guidance Subsystem"

[languages.en.params.logo]
logoText = "agren.cc"
logoHomeLink = "/"

[languages.en.menu]
[[languages.en.menu.main]]
identifier = "about"
name = "about"
url = "/about/index.html"
[[languages.en.menu.main]]
identifier = "mastodon"
name = "mastodon"
url = "https://telegrafverket.cc/@linus"
